# flake8: noqa: PYI021

from typing import Final, Sized

EARTH_RADIUS_METERS: Final[float]

# Opaque handle returned by Rust geometry factories. Placeholder until full
# geometry bindings land; stored by Python wrappers to keep lifetimes stable.
GeometryHandle = Sized

CRSLike = int | str | None


def distance(a: GeometryHandle, b: GeometryHandle, *, crs: CRSLike | None = ...) -> float: ...
def equals(a: GeometryHandle, b: GeometryHandle) -> bool: ...
def intersects(a: GeometryHandle, b: GeometryHandle) -> bool: ...
def within(a: GeometryHandle, b: GeometryHandle) -> bool: ...
def buffer(geometry: GeometryHandle, distance_meters: float) -> GeometryHandle: ...
def centroid(geometry: GeometryHandle) -> GeometryHandle: ...
